# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkadvisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.IntegerField(default=0)),
                ('caffeine', models.IntegerField(default=0)),
                ('isEnergyDrink', models.BooleanField(default=False)),
                ('isSugarFree', models.BooleanField(default=False)),
                ('date_uploaded', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('rate', models.IntegerField(null=True)),
                ('date_uploaded', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinkadvisor.Drink')),
            ],
        ),
    ]
